### ISSUE TITLE
Progress bar color update method not working!

### ISSUE THREAD

**Issue by darshana-hub** [CodyHouse/cd-progress-bar-changelog#1]
Hello, I have added color updated method of progress bar in my website but it just displays simple progress bar without animation from lower percentage to higher. It displays color perfectly just animation is not working. I have used code of demo page.
```
<div class="progress-bar progress-bar--color-update flex flex-column items-center js-progress-bar">
                      <p class="sr-only" aria-live="polite" aria-atomic="true">Progress value is <span class="js-progress-bar__aria-value"><?=$percent?>%</span></p>

                      <span class="progress-bar__value margin-bottom-xs" aria-hidden="true"><?=$percent?>%</span>

                      <div class="progress-bar__bg " aria-hidden="true">
                        <div class="progress-bar__fill " style="width: <?=$percent?>%;"></div>
                      </div>
                    </div>
```
Where, <?=$percent?> will print the value to be displayed as percentage. Value is perfect i tried with static value also but it didnt worked. Here is the screenshot.
![screnshot](https://user-images.githubusercontent.com/59651042/115229124-4ac72780-a130-11eb-98cc-530596510817.png)
Please help me with what am i missing there. One more thing, when i try progress bar with animation demo with "data-animation='on'" it doesn't display percentage and displays NaN. 
```
<div class="progress-bar flex flex-column items-center js-progress-bar" data-animation="on">
  <p class="sr-only" aria-live="polite" aria-atomic="true">Progress value is <span class="js-progress-bar__aria-value">50%</span></p>

  <span class="progress-bar__value margin-bottom-xs" aria-hidden="true">50%</span>

  <div class="progress-bar__bg " aria-hidden="true">
    <div class="progress-bar__fill " style="width: 50%;"></div>
  </div>
</div>
```
Here attaching screenshot of that too.
![animation](https://user-images.githubusercontent.com/59651042/115229512-c3c67f00-a130-11eb-838b-f9e9fe03ebbc.png)

**Comment by claudia-romano** [comment]
Hi there,
the color-update variation is used to set a different color for the progress bar based on its value, but it does not animate the progress bar. So the first block of code you provided is working fine as it is showing the right percentage value with the right color. 

If you want to animate it, you will need to add the  `"data-animation='on'"` attribute.

If you get a NaN, make sure to try with a static value, not <?=$percent?>% as it is probabily converted after the script runs (<?=$percent?>% is not a number which explains the error). 

In this case, you will need to dynamically update the progress bar once <?=$percent?>% has been evaluated, as explained in the component Info page:
https://codyhouse.co/ds/components/info/progress-bar

**Comment by claudia-romano** [comment]
Closing this as no additional info was provided. Feel free to reopen it if you are still experiencing this issue. Cheers!
