### ISSUE TITLE
percentage with comma

### ISSUE THREAD

**Issue by kunturi75** [CodyHouse/cd-progress-bar-changelog#2]
Hi,
how do i print the percentage with the comma up to the decimal? In the html code I have entered this:
<div class = "progress-bar__fill" style = "width: 10.2%;"> </div>
and I get printed 10.238095238095237%

**Comment by claudia-romano** [comment]
Hi there, unfortunately the code you entered is not visible and I was not able to replicate the issue on my side. 

Could you provide more details about the issue? For example, what version are you using (default, animate, color update)? Thanks

**Comment by claudia-romano** [comment]
Hi there, I'm closing this issue since no additional info was provided. Feel free to reopen it if you are still having problems. Cheers!
