### ISSUE TITLE
.progress-bar__bg.offsetWidth returns 0

### ISSUE THREAD

**Issue by yankeyhotel** [CodyHouse/cd-progress-bar-changelog#3]
```
function getProgressBarValue(progressBar) {
    // get progress value
    // return (fill width/total width) * 100
    console.log(
      progressBar.element.getElementsByClassName("progress-bar__bg")[0]
        .offsetWidth
    );
    return parseFloat(
      (progressBar.fill.offsetWidth * 100) /
        progressBar.element.getElementsByClassName("progress-bar__bg")[0]
          .offsetWidth
    );
  }
  ```
  
For some reason, `progressBar.element.getElementsByClassName("progress-bar__bg")[0].offsetWidth` always returns `0` This prevents the animation from happening and returns `NAN%` over the progress bar.

I have no customization and am just pasting in directly the code from Codyhouse v3.

**Comment by claudia-romano** [comment]
Hi there, the width of the `.progress-bar__bg` is set to be equal to the `--progress-bar-width` property. Is this set on your side as well? If you remove the JS of the component, does the `.progress-bar__bg` have the proper width?
